name: spike_interface
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - blas=2.106
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - colorama=0.4.6
  - comm=0.2.2
  - cuda-cccl=12.8.90
  - cuda-cccl_win-64=12.8.90
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.8.90
  - cuda-runtime=11.8.0
  - cuda-version=12.8
  - debugpy=1.8.1
  - decorator=5.1.1
  - executing=2.0.1
  - filelock=3.18.0
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - intel-openmp=2025.0.4
  - ipykernel=6.29.3
  - ipython=8.24.0
  - jedi=0.19.1
  - jinja2=3.1.6
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - krb5=1.21.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.9.90
  - libcurand-dev=10.3.9.90
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libffi=3.4.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libuv=1.50.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.10.14
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyzmq=26.0.3
  - setuptools=69.5.1
  - six=1.16.0
  - stack_data=0.6.2
  - tbb=2021.13.0
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.3
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - pip:
    - annotated-types==0.7.0
    - asciitree==0.3.3
    - boto3==1.34.102
    - botocore==1.34.102
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - colorlog==6.8.2
    - contourpy==1.2.1
    - cryptography==42.0.7
    - cuda-python==12.4.0
    - cycler==0.12.1
    - cython==0.29.37
    - dask==2024.5.0
    - distinctipy==1.3.4
    - docker==7.0.0
    - exceptiongroup==1.2.1
    - faiss-cpu==1.10.0
    - fasteners==0.19
    - flake8==7.0.0
    - fonttools==4.51.0
    - fsspec==2024.3.1
    - globus-sdk==3.41.0
    - h5py==3.11.0
    - hdbscan==0.8.33
    - huggingface-hub==0.31.2
    - ibl-neuropixel==1.0.0
    - iblatlas==0.5.1
    - ibllib==2.35.1
    - iblutil==1.8.0
    - idna==3.7
    - imageio==2.34.1
    - iniconfig==2.0.0
    - jmespath==1.0.1
    - joblib==1.4.2
    - kilosort==4.0.30
    - kiwisolver==1.4.5
    - lazy-loader==0.4
    - llvmlite==0.42.0
    - locket==1.0.0
    - matplotlib==3.8.4
    - mccabe==0.7.0
    - mtscomp==1.0.2
    - neo==0.14.2
    - networkx==3.3
    - neurodsp==2.3.0
    - nptdms==1.9.0
    - nptyping==2.5.0
    - numba==0.59.1
    - numcodecs==0.12.1
    - numpy==1.26.4
    - one-api==2.7.0
    - open-ephys-python-tools==0.1.12
    - opencv-python-headless==4.9.0.80
    - pandas==2.2.2
    - partd==1.4.2
    - phylib==2.4.3
    - pillow==10.3.0
    - pluggy==1.5.0
    - probeinterface==0.3.0
    - psychofit==1.0.0.post0
    - pyarrow==16.0.0
    - pycodestyle==2.11.1
    - pycparser==2.22
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pyflakes==3.2.0
    - pyjwt==2.8.0
    - pynrrd==1.0.0
    - pyparsing==3.1.2
    - pyqt5==5.15.10
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.13.0
    - pyqtgraph==0.13.7
    - pyside6==6.9.0
    - pyside6-addons==6.9.0
    - pyside6-essentials==6.9.0
    - pytest==8.2.0
    - python-dateutil==2.9.0.post0
    - python-graphviz==0.20.3
    - pytz==2024.1
    - pywin32==306
    - pyyaml==6.0.1
    - quantities==0.16.1
    - requests==2.31.0
    - s3transfer==0.10.1
    - scikit-image==0.23.2
    - scikit-learn==1.4.2
    - scipy==1.12.0
    - seaborn==0.13.2
    - shiboken6==6.9.0
    - skops==0.11.0
    - slidingrp==1.0.0
    - sparse==0.15.1
    - spikeinterface==0.103.0
    - spikeinterface-gui==0.10.0
    - sympy==1.13.1
    - tabulate==0.9.0
    - threadpoolctl==3.5.0
    - tifffile==2024.5.10
    - tomli==2.0.1
    - toolz==0.12.1
    - tqdm==4.66.4
    - typing-extensions==4.15.0
    - typing-inspection==0.4.1
    - tzdata==2024.1
    - urllib3==2.2.1
    - zarr==2.18.0
    - zipp==3.18.1
    - zmq==0.0.0
prefix: C:\Users\neuroPC\anaconda3\envs\spike_interface
