name: ephys
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - libsqlite=3.51.0
  - libzlib=1.3.1
  - openssl=3.6.0
  - pip=25.3
  - python=3.12.12
  - setuptools=80.9.0
  - tk=8.6.13
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.45.1
  - pip:
    - altair==6.0.0
    - annotated-types==0.7.0
    - anyio==4.11.0
    - asciitree==0.3.3
    - asttokens==3.0.1
    - attrs==25.4.0
    - boto3==1.41.2
    - botocore==1.41.2
    - certifi==2025.11.12
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - click==8.3.1
    - cloudpickle==3.1.2
    - colorama==0.4.6
    - colorcet==3.1.0
    - colorlog==6.10.1
    - comm==0.2.3
    - contourpy==1.3.3
    - cryptography==46.0.3
    - cuda-bindings==13.0.3
    - cuda-pathfinder==1.3.2
    - cuda-python==13.0.3
    - cycler==0.12.1
    - dask==2025.11.0
    - decorator==5.2.1
    - deprecated==1.3.1
    - distinctipy==1.3.4
    - docker==7.1.0
    - executing==2.2.1
    - fasteners==0.20
    - figrid==0.1.7
    - figurl==0.3.1
    - filelock==3.20.0
    - flake8==7.3.0
    - fonttools==4.60.1
    - fsspec==2025.10.0
    - globus-sdk==4.1.0
    - h11==0.16.0
    - h5py==3.15.1
    - hdbscan==0.8.40
    - hdmf==4.1.2
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==1.1.5
    - ibl-neuropixel==1.9.1
    - ibl-style==0.1.0
    - iblatlas==0.10.0
    - ibllib==3.4.1
    - iblqt==0.8.2
    - iblutil==1.20.0
    - idna==3.11
    - imagecodecs==2025.11.11
    - imageio==2.37.2
    - iniconfig==2.3.0
    - ipympl==0.9.8
    - ipython==9.7.0
    - ipython-pygments-lexers==1.1.1
    - ipywidgets==8.1.8
    - jedi==0.19.2
    - jinja2==3.1.6
    - jmespath==1.0.1
    - joblib==1.5.2
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyterlab-widgets==3.0.16
    - kachery==2.0.2
    - kiwisolver==1.4.9
    - lazy-loader==0.4
    - llvmlite==0.45.1
    - locket==1.0.0
    - markdown==3.10
    - markupsafe==3.0.3
    - matplotlib==3.10.7
    - matplotlib-inline==0.2.1
    - mccabe==0.7.0
    - mtscomp==1.0.2
    - narwhals==2.12.0
    - neo==0.14.3
    - networkx==3.5
    - nptdms==1.10.0
    - numba==0.62.1
    - numcodecs==0.15.1
    - numpy==2.2.0
    - one-api==3.4.1
    - open-ephys-python-tools==1.0.1
    - opencv-python-headless==4.12.0.88
    - packaging==25.0
    - pandas==2.3.3
    - parso==0.8.5
    - partd==1.4.2
    - patsy==1.0.2
    - phylib==2.6.3
    - pillow==12.0.0
    - platformdirs==4.5.0
    - pluggy==1.6.0
    - prettytable==3.17.0
    - probeinterface==0.3.1
    - prompt-toolkit==3.0.52
    - psychofit==1.0.0.post0
    - pure-eval==0.2.3
    - pyarrow==22.0.0
    - pycodestyle==2.14.0
    - pycparser==2.23
    - pydantic==2.12.4
    - pydantic-core==2.41.5
    - pyflakes==3.4.0
    - pygments==2.19.2
    - pyjwt==2.10.1
    - pynrrd==1.1.3
    - pynwb==3.1.2
    - pyparsing==3.2.5
    - pyqt5==5.15.11
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.17.1
    - pyqtgraph==0.14.0
    - pyside6==6.10.1
    - pyside6-addons==6.10.1
    - pyside6-essentials==6.10.1
    - pytest==9.0.1
    - python-dateutil==2.9.0.post0
    - python-graphviz==0.21
    - pytz==2025.2
    - pywin32==311
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - qtpy==2.4.3
    - quantities==0.16.2
    - referencing==0.37.0
    - requests==2.32.5
    - responses==0.25.8
    - rpds-py==0.29.0
    - ruamel-yaml==0.18.16
    - ruamel-yaml-clib==0.2.15
    - ruff==0.14.6
    - s3transfer==0.15.0
    - scikit-image==0.25.2
    - scikit-learn==1.7.2
    - scipy==1.16.3
    - seaborn==0.13.2
    - shellingham==1.5.4
    - shiboken6==6.10.1
    - simplejson==3.20.2
    - six==1.17.0
    - skops==0.13.0
    - slidingrp==1.1.1
    - sniffio==1.3.1
    - sortingview==0.14.2
    - sparse==0.17.0
    - spikeinterface==0.103.1
    - spikeinterface-gui==0.12.0
    - stack-data==0.6.3
    - statsmodels==0.14.5
    - threadpoolctl==3.6.0
    - tifffile==2025.10.16
    - toolz==1.1.0
    - tqdm==4.67.1
    - traitlets==5.14.3
    - typer-slim==0.20.0
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - urllib3==2.5.0
    - wcwidth==0.2.14
    - widgetsnbextension==4.0.15
    - wrapt==2.0.1
    - zarr==2.18.7
    - zmq==0.0.0
prefix: C:\Users\neuroPC\anaconda3\envs\ephys
